src/Entity/Car.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CarRepository")
 */
class Car
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $keywords;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $marka;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $model;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $location;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="cars")
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $status;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $detail;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="car")
     */
    private $images;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $userid;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $price;

    public function __construct()
    {
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getKeywords(): ?string
    {
        return $this->keywords;
    }

    public function setKeywords(string $keywords): self
    {
        $this->keywords = $keywords;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getMarka(): ?string
    {
        return $this->marka;
    }

    public function setMarka(?string $marka): self
    {
        $this->marka = $marka;

        return $this;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(?string $model): self
    {
        $this->model = $model;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getDetail(): ?string
    {
        return $this->detail;
    }

    public function setDetail(?string $detail): self
    {
        $this->detail = $detail;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setCar($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getCar() === $this) {
                $image->setCar(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        // TODO: Implement __toString() method.
        return $this->getImage();
    }

    public function getUserid(): ?int
    {
        return $this->userid;
    }

    public function setUserid(?int $userid): self
    {
        $this->userid = $userid;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(?float $price): self
    {
        $this->price = $price;

        return $this;
    }
}

src/Controller/Admin/CarController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Car;
use App\Form\CarType;
use App\Repository\CarRepository;
use phpDocumentor\Reflection\File;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("admin/car")
 */
class CarController extends AbstractController
{
    /**
     * @Route("/", name="admin_car_index", methods={"GET"})
     */
    public function index(CarRepository $carRepository): Response
    {
        $cars = $carRepository->getAllCars();
        return $this->render('admin/car/index.html.twig', [
            'cars' => $cars
        ]);
    }

    /**
     * @Route("/new", name="admin_car_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $car = new Car();
        $form = $this->createForm(CarType::class, $car);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            //************file upload***************************************
            /** @var file $file */
            $file = $form['image']->getData();
            if($file){
                $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();
                // this is needed to safely include the file name as part of the URL
                try{
                    $file->move(
                        $this->getParameter('images_directory'),
                        $fileName
                    );
                }catch(FileException $e){

                }
                $car->setImage($fileName);
            }
            //********file upload*************************************************
            $entityManager->persist($car);
            $entityManager->flush();

            return $this->redirectToRoute('admin_car_index');
        }

        return $this->render('admin/car/new.html.twig', [
            'car' => $car,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_car_show", methods={"GET"})
     */
    public function show(Car $car): Response
    {
        return $this->render('admin/car/show.html.twig', [
            'car' => $car,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="admin_car_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Car $car): Response
    {
        $form = $this->createForm(CarType::class, $car);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            /** @var file $file */
            $file = $form['image']->getData();
            if($file){
                $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();
                try{
                    $file->move(
                        $this->getParameter('images_directory'),
                        $fileName
                    );
                }catch(FileException $e){

                }
                $car->setImage($fileName);
            }

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('admin_car_index');
        }

        return $this->render('admin/car/edit.html.twig', [
            'car' => $car,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @return string
     */
    private function generateUniqueFileName(){

        return md5(uniqid());
    }

    /**
     * @Route("/{id}", name="admin_car_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Car $car): Response
    {
        if ($this->isCsrfTokenValid('delete'.$car->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($car);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_car_index');
    }
}

src/Controller/CarController.php
<?php

namespace App\Controller;

use App\Entity\Car;
use App\Form\Car1Type;
use App\Repository\CarRepository;
use phpDocumentor\Reflection\File;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/user/car")
 */
class CarController extends AbstractController
{
    /**
     * @Route("/", name="user_car_index", methods={"GET"})
     */
    public function index(CarRepository $carRepository): Response
    {
        $user = $this->getUser();
        return $this->render('car/index.html.twig', [
            'cars' => $carRepository->findBy(['userid'=>$user->getId()]),
        ]);
    }

    /**
     * @Route("/new", name="user_car_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $car = new Car();
        $form = $this->createForm(Car1Type::class, $car);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $car->setStatus('new');
            //************file upload
            /** @var file $file */
            $file = $form['image']->getData();
            if($file){
                $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();
                // this is needed to safely include the file name as part of the URL
                try{
                    $file->move(
                        $this->getParameter('images_directory'),
                        $fileName
                    );
                }catch(FileException $e){

                }
                $car->setImage($fileName);
            }
            //********file upload
            $user = $this->getUser();
            $car->setUserid($user->getid());

            $car->setStatus("new");

            $entityManager->persist($car);
            $entityManager->flush();

            return $this->redirectToRoute('user_car_index');
        }

        return $this->render('car/new.html.twig', [
            'car' => $car,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_car_show", methods={"GET"})
     */
    public function show(Car $car): Response
    {
        return $this->render('car/show.html.twig', [
            'car' => $car,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="user_car_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Car $car): Response
    {
        $form = $this->createForm(Car1Type::class, $car);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //************file upload
            /** @var file $file */
            $file = $form['image']->getData();
            if($file){
                $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();
                // this is needed to safely include the file name as part of the URL
                try{
                    $file->move(
                        $this->getParameter('images_directory'),
                        $fileName
                    );
                }catch(FileException $e){

                }
                $car->setImage($fileName);
            }
            //********file upload
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_car_index');
        }

        return $this->render('car/edit.html.twig', [
            'car' => $car,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @return string
     */
    private function generateUniqueFileName(){

        return md5(uniqid());
    }

    /**
     * @Route("/{id}", name="user_car_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Car $car): Response
    {
        if ($this->isCsrfTokenValid('delete'.$car->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($car);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_car_index');
    }
}

templates/car/_delete_form.html.twig
<form method="post" action="{{ path('user_car_delete', {'id': car.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ car.id) }}">
    <button class="btn">Delete</button>
</form>

templates/car/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/car/edit.html.twig
{% extends 'homebase.html.twig' %}

{% block title %} {{ app.user.name }} Cars {% endblock %}

{% block body %}
    <section id="subintro">
        <div class="jumbotron subhead" id="overview">
            <div class="container">
                <div class="row">
                    <div class="span12">
                        <div class="centered">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section id="breadcrumb">
        <div class="container">
            <div class="row">
                <div class="span12">
                    <ul class="breadcrumb notop">
                        <li><a href="#">Home</a><span class="divider">/</span></li>
                        <li class="active">Blog left sidebar</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <section id="maincontent">
        <div class="container">
            <div class="row">

                {{ include ('user/usermenu.html.twig') }}

                <div class="span7">
                    <!-- start article 1 -->
                    <article class="blog-post">
                        <div class="post-heading">
                            <h3><a href="#">Edit Cars</a></h3>
                        </div>
                        <div class="row">
                            <div class="span8">

                                {{ include('car/_form.html.twig', {'button_label': 'Update'}) }}

                                <a href="{{ path('user_car_index') }}">back to list</a>

                                {{ include('car/_delete_form.html.twig') }}
                            </div>
                        </div>
                    </article>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/car/index.html.twig
{% extends 'homebase.html.twig' %}

{% block title %} {{ app.user.name }} Cars {% endblock %}

{% block body %}
    <SCRIPT language="JavaScript" type="text/javascript">
        function openWin(windowUrl, windowName, windowFeatures) { window.open(windowUrl, windowName, windowFeatures);}
    </SCRIPT>
    <section id="subintro">
        <div class="jumbotron subhead" id="overview">
            <div class="container">
                <div class="row">
                    <div class="span12">
                        <div class="centered">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section id="breadcrumb">
        <div class="container">
            <div class="row">
                <div class="span12">
                    <ul class="breadcrumb notop">
                        <li><a href="#">Home</a><span class="divider">/</span></li>
                        <li class="active">Cars</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <section id="maincontent">
        <div class="container">
            <div class="row">

                {{ include ('user/usermenu.html.twig') }}

                <div class="span7">
                    <!-- start article 1 -->
                    <article class="blog-post">
                        <div class="post-heading">
                            <h3><a href="#">My Cars</a></h3>
                        </div>
                        <div class="row">
                            <div class="span8">

                                <div class="col-md-2">
                                    <a href="{{ path('user_car_new') }}" class="btn btn-block btn-info">Create new</a>
                                </div>
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Title</th>
                                        <th>Image</th>
                                        <th>Marka</th>
                                        <th>Model</th>
                                        <th>I.Galerry</th>
                                        <th>Status</th>
                                        <th>actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for car in cars %}
                                        <tr>
                                            <td>{{ car.id }}</td>
                                            <td>{{ car.title }}</td>
                                            <td>
                                                <img src="{{asset('uploads/' ~ car.image )}}" height="40">
                                            </td>
                                            <td>{{ car.marka }}</td>
                                            <td>{{ car.model }}</td>
                                            <td>
                                                <a href="javascript:openWin('{{ path('user_image_new', {'id': car.id }) }}','','toolbar=no,location=no,directories=0,status=no,top=50,left=100,menuBar=no,scrollBars=yes,resizable=no,width=900,height=600');">
                                                    <img src="{{ asset('images') }}/gallery.jpg" height="40">
                                                </a>
                                            </td>
                                            <td>{{ car.status }}</td>
                                            <td>
                                                <a href="{{ path('user_car_show', {'id': car.id}) }}" class="btn btn-block btn-info">show</a>
                                            </td>
                                            <td>
                                                <a href="{{ path('user_car_edit', {'id': car.id}) }}" class="btn btn-block btn-info">edit</a>
                                            </td>
                                        </tr>
                                    {% else %}
                                        <tr>
                                            <td colspan="16">no records found</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>


                            </div>
                        </div>
                    </article>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/car/new.html.twig
{% extends 'homebase.html.twig' %}

{% block title %}Show {{ app.user.name }} Cars {% endblock %}

{% block body %}
    <section id="subintro">
        <div class="jumbotron subhead" id="overview">
            <div class="container">
                <div class="row">
                    <div class="span12">
                        <div class="centered">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section id="breadcrumb">
        <div class="container">
            <div class="row">
                <div class="span12">
                    <ul class="breadcrumb notop">
                        <li><a href="#">Home</a><span class="divider">/</span></li>
                        <li class="active">Blog left sidebar</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <section id="maincontent">
        <div class="container">
            <div class="row">

                {{ include ('user/usermenu.html.twig') }}

                <div class="span7">
                    <!-- start article 1 -->
                    <article class="blog-post">
                        <div class="post-heading">
                            <h3><a href="#">New Car</a></h3>
                        </div>
                        <div class="row">
                            <div class="span8">
                                <h1>Create new Car</h1>

                                {{ include('car/_form.html.twig') }}

                                <a href="{{ path('user_car_index') }}">back to list</a>
                            </div>
                        </div>
                    </article>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/car/show.html.twig
{% extends 'homebase.html.twig' %}

{% block title %} {{ app.user.name }} Car {% endblock %}

{% block body %}
    <section id="subintro">
        <div class="jumbotron subhead" id="overview">
            <div class="container">
                <div class="row">
                    <div class="span12">
                        <div class="centered">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section id="breadcrumb">
        <div class="container">
            <div class="row">
                <div class="span12">
                    <ul class="breadcrumb notop">
                        <li><a href="#">Home</a><span class="divider">/</span></li>
                        <li class="active">Blog left sidebar</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <section id="maincontent">
        <div class="container">
            <div class="row">

                {{ include ('user/usermenu.html.twig') }}

                <div class="span7">
                    <!-- start article 1 -->
                    <article class="blog-post">
                        <div class="post-heading">
                            <h3><a href="#">My Car</a></h3>
                        </div>
                        <div class="row">
                            <div class="span8">
                                <table class="table">
                                    <tbody>
                                    <tr>
                                        <th>Id</th>
                                        <td>{{ car.id }}</td>
                                    </tr>
                                    <tr>
                                        <th>Title</th>
                                        <td>{{ car.title }}</td>
                                    </tr>
                                    <tr>
                                        <th>Keywords</th>
                                        <td>{{ car.keywords }}</td>
                                    </tr>
                                    <tr>
                                        <th>Description</th>
                                        <td>{{ car.description }}</td>
                                    </tr>
                                    <tr>
                                        <th>Image</th>
                                        <td>{{ car.image }}</td>
                                    </tr>
                                    <tr>
                                        <th>Marka</th>
                                        <td>{{ car.marka }}</td>
                                    </tr>
                                    <tr>
                                        <th>Model</th>
                                        <td>{{ car.model }}</td>
                                    </tr>
                                    <tr>
                                        <th>Phone</th>
                                        <td>{{ car.phone }}</td>
                                    </tr>
                                    <tr>
                                        <th>Email</th>
                                        <td>{{ car.email }}</td>
                                    </tr>
                                    <tr>
                                        <th>City</th>
                                        <td>{{ car.city }}</td>
                                    </tr>
                                    <tr>
                                        <th>Country</th>
                                        <td>{{ car.country }}</td>
                                    </tr>
                                    <tr>
                                        <th>Location</th>
                                        <td>{{ car.location }}</td>
                                    </tr>
                                    <tr>
                                        <th>Status</th>
                                        <td>{{ car.status }}</td>
                                    </tr>
                                    <tr>
                                        <th>Created_at</th>
                                        <td>{{ car.createdAt ? car.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                                    </tr>
                                    <tr>
                                        <th>Updated_at</th>
                                        <td>{{ car.updatedAt ? car.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                                    </tr>
                                    <tr>
                                        <th>Detail</th>
                                        <td>{{ car.detail | raw}}</td>
                                    </tr>
                                    <tr>
                                        <th>Userid</th>
                                        <td>{{ car.userid }}</td>
                                    </tr>
                                    </tbody>
                                </table>

                                <a href="{{ path('user_car_index') }}">back to list</a>

                                <a href="{{ path('user_car_edit', {'id': car.id}) }}">edit</a>

                                {{ include('car/_delete_form.html.twig') }}


                            </div>
                        </div>
                    </article>
                </div>
            </div>
        </div>
    </section>

{% endblock %}